#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.powerbuttons"
CFG="$HOME/.config/eww/powerbuttons"
EWW="$HOME/.local/bin/eww"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

${EWW} --config "$CFG" open-many background shutdown reboot logoff sleep
