#!/bin/bash

read type name <<< $(nmcli -t -f DEVICE,TYPE,STATE,CONNECTION device | grep ':connected:' | grep -v '^lo' | awk -F':' '{print $2, $4}')

if [ -z "$type" ]; then
    echo "TYPE=disconnected"
    echo "NAME=disc"
else
    echo "TYPE=$type"
    echo "NAME=$name"
fi