#!/bin/bash

SUCCESS="(˶ᵔ ᵕ ᵔ˶)"
NOT_FOUND="( ╹ -╹)?"

# install packages
packages=$(cat "./packages" | grep -v "#")
yay -S $packages

# install config folders
for source in $(find .config/ -maxdepth 1 ! -path .config/); do
  if [ -d "$source" ]; then
    cp -r "$source" "/home/$USER/.config/"
    echo "$SUCCESS config folder installed [$source]"
  elif [ -f "$source" ]; then
    cp "$source" "/home/$USER/.config/"
    echo "$SUCCESS config file installed [$source]"    
  else
    echo "[$source] not found"
  fi
done

# copy wallpapers

# add system services (startups)

 
