#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.powerbuttons"
CFG="$HOME/.config/eww/powerbuttons"
EWW="$HOME/.local/bin/eww"

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

run_eww() {
    ${EWW} --config "$CFG" open-many background shutdown reboot logoff sleep
}

if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    ${EWW} --config "$CFG" close background shutdown reboot logoff sleep
    rm "$FILE"
fi
