[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]

[[language]]
name = "python"
language-servers = ["ruff", "pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.qmlls]
args = ["-E"]
command = "qmlls"
