## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "rw1c"

# Setups
format="""
$directory\ 
$character\
"""
right_format = """
$git_branch\
"""
add_newline = false 

# Other languages configurations:
c.disabled = true
cmake.disabled = true
haskell.disabled = true
python.disabled = true
ruby.disabled = true
rust.disabled = true
perl.disabled = true
package.disabled = true
lua.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[username]
show_always = true
style_user = "fg:text bold"
style_root = "fg:text bold"
format = '[$user]($style)'
disabled = false

[conda]
format = ' [$symbol$environment](dimmed green) '

# Prompt symbols 
[character]
success_symbol = "[ 󰄛](green bold)"
error_symbol = "[ 󰄛](lred)"
vicmd_symbol = "[ 󰄛](peach)"

[directory]
format = "[  ](bg:transparent fg:text)[$path](bg:transparent fg:text bold)"
style = "bg:none fg:dblue"
truncation_length = 3
truncate_to_repo=false

[git_branch]
format = "[[ ](fg:purple bold)$branch](fg:purple bold)"
style = "bg:none fg:base"

[git_status]
# $all status$ahead_behind
format = "[$all_status$ahead_behind](bg:base fg:purple) "
style = "bg:none fg:base"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[palettes.rw1c]
black  = "#222831"
red = "#F4A3A3"
green = "#D4E3A8"
yellow = "#E8BC7A"
blue = "#B8E5E7"
purple = "#9582B7"
cyan = "#52D6D3"
white = "#FAF0E7"

goldish = "#E5B566"
dblue = "#17121C"
lred = "#F53C3C"

text = "#F4A3A3"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1d1d27"
mantle = "#181825"
crust = "#11111b"