#!/bin/bash

SOURCE="../.config"
TARGET="/home/$USER/.config/"
SUCCESS="(˶ᵔ ᵕ ᵔ˶)"
NOT_FOUND="( ╹ -╹)?"

# install config folders
for source in $(ls ../home/.config); do
  if [ -d "../home/.config/$source" ]; then
    cp -r "../home/.config/$source" "/home/$USER/.config/"
    echo "$SUCCESS config folder installed [$source]"
  elif [ -f "../home/.config/$source" ]; then
    cp "../home/.config/$source" "/home/$USER/.config/"
    echo "$SUCCESS config file installed [$source]"    
  else
    echo "[$source] not found"
  fi
done
