#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	echo "∠( ᐛ 」∠)_ Please run as root"
	exit 1
fi

# copies .service files to the /etc/systemd/system folder
# activates teach service

TARGET=/etc/systemd/system
SOURCE=../etc/systemd

for service in $(ls $SOURCE | grep ".service"); do
  cp $SOURCE/$service $TARGET
  echo "(　･ω･)☞ found $service" 
done

echo "Reloading systemd daemon"
systemctl daemon-reload

for service in $(ls $SOURCE | grep ".service"); do
  systemctl enable $service
  echo "ଘ(੭ˊᵕˋ)੭* ੈ✩‧₊˚ $service enabled"
done
