name = "bunny_dark_v2"
author = "Bunny"

"type" = "accent_soft"
"constant" = "accent"
"constant.numeric" = "complementary"
"constant.character.escape" = "highlight"
"string" = "complementary"
"string.regexp" = "complementary_soft"
"comment" = "foreground_muted"
"variable" = "foreground"
"variable.builtin" = "complementary_soft"
"variable.parameter" = "foreground"
"variable.other.member" = "foreground"
"label" = "complementary"
"punctuation" = "foreground_muted"
"punctuation.delimiter" = "foreground_muted"
"punctuation.bracket" = "foreground"
"keyword" = "accent"
"keyword.directive" = "highlight"
"operator" = "warning"
"function" = "highlight"
"function.builtin" = "highlight"
"function.macro" = "highlight"
"tag" = "accent_soft"
"namespace" = "warning"
"attribute" = "highlight"
"constructor" = "accent_soft"
"module" = "warning"
"special" = "complementary"

"markup.heading.marker" = "foreground_muted"
"markup.heading.1" = { fg = "accent", modifiers = ["bold"] }
"markup.heading.2" = { fg = "warning", modifiers = ["bold"] }
"markup.heading.3" = { fg = "highlight", modifiers = ["bold"] }
"markup.heading.4" = { fg = "accent_soft", modifiers = ["bold"] }
"markup.heading.5" = { fg = "complementary", modifiers = ["bold"] }
"markup.heading.6" = { fg = "foreground", modifiers = ["bold"] }
"markup.list" = "warning"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.url" = { fg = "complementary", modifiers = ["underlined"] }
"markup.link.text" = "accent"
"markup.quote" = "foreground_muted"
"markup.raw" = "complementary"

"diff.plus" = "complementary"
"diff.delta" = "complementary_soft"
"diff.minus" = "warning"

"ui.background" = { bg = "transparent" }
"ui.background.separator" = "border"
"ui.cursor" = { fg = "bg0", bg = "foreground" }
"ui.cursor.match" = { fg = "complementary", bg = "accent_soft" }
"ui.cursor.insert" = { fg = "black", bg = "foreground_muted" }
"ui.cursor.select" = { fg = "bg0", bg = "highlight" }
"ui.cursorline.primary" = { bg = "bg1" }
"ui.cursorline.secondary" = { bg = "bg1" }
"ui.selection" = { bg = "bg4" }
"ui.linenr" = "foreground_muted"
"ui.linenr.selected" = "foreground"
"ui.statusline" = { fg = "foreground", bg = "bg3" }
"ui.statusline.inactive" = { fg = "foreground_muted", bg = "bg1" }
"ui.statusline.normal" = { fg = "bg0", bg = "foreground", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg0", bg = "accent", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg0", bg = "highlight", modifiers = ["bold"] }
"ui.bufferline" = { fg = "foreground_muted", bg = "bg1" }
"ui.bufferline.active" = { fg = "foreground", bg = "bg4", modifiers = ["bold"] }
"ui.popup" = { fg = "foreground_muted", bg = "bg2" }
"ui.window" = { fg = "foreground_muted", bg = "bg0" }
"ui.help" = { fg = "foreground", bg = "bg2" }
"ui.text" = "foreground"
"ui.text.focus" = "complementary"
"ui.menu" = { fg = "foreground", bg = "bg3" }
"ui.menu.selected" = { fg = "bg0", bg = "highlight" }
"ui.virtual.whitespace" = { fg = "bg4" }
"ui.virtual.indent-guide" = { fg = "bg4" }
"ui.virtual.ruler" = { bg = "bg2" }

"hint" = "highlight"
"info" = "complementary"
"warning" = "warning"
"error" = "warning"
"diagnostic" = { underline = { style = "line" } }
"diagnostic.hint" = { underline = { color = "highlight", style = "dotted" } }
"diagnostic.info" = { underline = { color = "complementary", style = "dotted" } }
"diagnostic.warning" = { underline = { color = "warning", style = "curl" } }
"diagnostic.error" = { underline = { color = "warning", style = "curl" } }

[palette]
accent = "#8B6FB4"
accent_dark = "#6E5898"
accent_soft = "#B7A1D3"
accent_pink = "#C6A5BC"

foreground = "#E6DFF0"
foreground_muted = "#BFB3CB"

complementary = "#789659"
complementary_soft = "#9BB27A"
complementary_foreground = "#DAE8D0"

highlight = "#6BB9A7"
warning = "#D46A8C"
success = "#A4CE70"

border = "#4B4354"
grey = "#A89DB2"
black = "#000000"

bg0 = "#17131A"
bg1 = "#221B26"
bg2 = "#2B2330"
bg3 = "#302838"
bg4 = "#3B3145"
